[package]
name = "jsii_rust_runtime"
version = "0.1.0"
authors = ["jsii"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
fs_extra = "1.1"
