[tasks.pre-build]
script_runner="@shell"
script = [
'''
lerna bootstrap --scope jsii-rust-runtime
'''
]

[tasks.pre_test]
script_runner="@shell"
script = [
'''
./node_modules/.bin/jsii-pacmak -t js -o target/jsii-calc --recurse node_modules/jsii-calc
'''
]
