[tasks.pre-build]
script_runner="@shell"
script = [
'''
lerna bootstrap --scope jsii-rust-runtime
'''
]

[tasks.pre_test]
script_runner="@shell"
dependencies = [
"pre-build"
]
script = [
'''
npm pack node_modules/jsii-calc/.
'''
]
